// Generated by CoffeeScript 1.8.0
(function() {
  var main;

/*
//http://d.hatena.ne.jp/IT7C/20160110/1452427165
chrome.tabs.captureVisibleTab(null, {}, function (image) {
   // You can add that image HTML5 canvas, or Element.
});

*/

  main = function() {
    /*
    chrome.storage.local.get('options', function(data) {
      return $('#form input').each(function() {
        this.checked = data.options[this.name];
        return null;
      });
    });
    */

    $('#cap').click(function(e) {
      var img = $("<img></img>", {
                  src: "",
                  width:"225",
                  height:"127"
                });
      var img_link = $("<a></a>", {
                  href: "",
                  target: "_blank"
                });
      chrome.tabs.captureVisibleTab(null, {format:"png"}, function (str) {

        img.attr('src',str);
        img_link.attr('href',str);
  		});
  		
  		//追加
  		img_link.append(img);
  		$('#images').append(img_link);
  		
      e.preventDefault();
      //run_checker(true);
    });
    return $('#inspect').click(function(e) {
      $('#name1').val('test');

      e.preventDefault();
      //run_checker(false);
    });
    

  };

  main();

}).call(this);
